import * as mongoose from 'mongoose';
import { Post } from '../model/events.model';

export const PostSchema = new mongoose.Schema<Post>({
  id: String,
  donoPost: {
    id: String,
    email: String,
    password: String,
    username: String,
    firstAccess: Boolean,
    setor: String,
    especialidades: {
      direito_administrativo: Boolean,
      direito_civil: Boolean,
      direito_minorias: Boolean,
      direito_empresarial: Boolean,
      propriedade_intelectual: Boolean,
      direito_ambiental: Boolean,
      direito_financeiro_tributário: Boolean,
      direito_processual: Boolean,
      direito_trabalho: Boolean,
      direito_previdenciário: Boolean,
      direito_constitucional: Boolean,
      direito_econômico_concorrencial: Boolean,
      direito_penal: Boolean,
      direito_anti_racismo: Boolean,
      direito_igualdade_genero: Boolean,
      filosofia_direito: Boolean,
      liderança: Boolean,
      eventos: Boolean,
      negociação: Boolean,
      mediação: Boolean,
      arbitragem: Boolean,
      gestão: Boolean,
      rh: Boolean,
      outros: { type: Map, of: Boolean },
    },
    hobbies: {
      violao: Boolean,
      violino: Boolean,
      surfar: Boolean,
      futebol: Boolean,
      livros: Boolean,
      musica: Boolean,
      esportes: Boolean,
      artes: Boolean,
      outros: { type: Map, of: Boolean },
    },
    profilePicture: String,
    currentJob: {
      empresa: String,
      setor: String,
      cargo: String,
      descricao: String,
      dataInicio: Date,
      dataFim: Date,
    },
    jobs: [
      {
        empresa: String,
        setor: String,
        cargo: String,
        descricao: String,
        dataInicio: Date,
        dataFim: Date,
      },
    ],
    formacao: [
      {
        tipo: String,
        instituicao: String,
        curso: String,
        descricao: String,
        dataInicio: Date,
        dataFim: Date,
      },
    ],
    genero: String,
    idiomas: {
      ingles: String,
      portugues: String,
      espanhol: String,
      alemao: String,
      frances: String,
      outros: { type: Map, of: String },
    },
    idealLocations: { maiorInteresse: String, interesse: [String] },
    funcionarioRh: Boolean,
  },
  tipoPost: String,
  comentarios: [
    {
      donoComentario: {
        id: String,
        email: String,
        password: String,
        username: String,
        firstAccess: Boolean,
        setor: String,
        especialidades: {
          direito_administrativo: Boolean,
          direito_civil: Boolean,
          direito_minorias: Boolean,
          direito_empresarial: Boolean,
          propriedade_intelectual: Boolean,
          direito_ambiental: Boolean,
          direito_financeiro_tributário: Boolean,
          direito_processual: Boolean,
          direito_trabalho: Boolean,
          direito_previdenciário: Boolean,
          direito_constitucional: Boolean,
          direito_econômico_concorrencial: Boolean,
          direito_penal: Boolean,
          direito_anti_racismo: Boolean,
          direito_igualdade_genero: Boolean,
          filosofia_direito: Boolean,
          liderança: Boolean,
          eventos: Boolean,
          negociação: Boolean,
          mediação: Boolean,
          arbitragem: Boolean,
          gestão: Boolean,
          rh: Boolean,
          outros: { type: Map, of: Boolean },
        },
        hobbies: {
          violao: Boolean,
          violino: Boolean,
          surfar: Boolean,
          futebol: Boolean,
          livros: Boolean,
          musica: Boolean,
          esportes: Boolean,
          artes: Boolean,
          outros: { type: Map, of: Boolean },
        },
        profilePicture: String,
        currentJob: {
          empresa: String,
          setor: String,
          cargo: String,
          descricao: String,
          dataInicio: Date,
          dataFim: Date,
        },
        jobs: [
          {
            empresa: String,
            setor: String,
            cargo: String,
            descricao: String,
            dataInicio: Date,
            dataFim: Date,
          },
        ],
        formacao: [
          {
            tipo: String,
            instituicao: String,
            curso: String,
            descricao: String,
            dataInicio: Date,
            dataFim: Date,
          },
        ],
        genero: String,
        idiomas: {
          ingles: String,
          portugues: String,
          espanhol: String,
          alemao: String,
          frances: String,
          outros: { type: Map, of: String },
        },
        idealLocations: { maiorInteresse: String, interesse: [String] },
        funcionarioRh: Boolean,
      },
      comentario: String,
      dataComentario: Date,
    },
  ],
  descricao: String,
  dataPost: Date,
  usuariosMarcados: [
    {
      id: String,
      email: String,
      password: String,
      username: String,
      firstAccess: Boolean,
      setor: String,
      especialidades: {
        direito_administrativo: Boolean,
        direito_civil: Boolean,
        direito_minorias: Boolean,
        direito_empresarial: Boolean,
        propriedade_intelectual: Boolean,
        direito_ambiental: Boolean,
        direito_financeiro_tributário: Boolean,
        direito_processual: Boolean,
        direito_trabalho: Boolean,
        direito_previdenciário: Boolean,
        direito_constitucional: Boolean,
        direito_econômico_concorrencial: Boolean,
        direito_penal: Boolean,
        direito_anti_racismo: Boolean,
        direito_igualdade_genero: Boolean,
        filosofia_direito: Boolean,
        liderança: Boolean,
        eventos: Boolean,
        negociação: Boolean,
        mediação: Boolean,
        arbitragem: Boolean,
        gestão: Boolean,
        rh: Boolean,
        outros: { type: Map, of: Boolean },
      },
      hobbies: {
        violao: Boolean,
        violino: Boolean,
        surfar: Boolean,
        futebol: Boolean,
        livros: Boolean,
        musica: Boolean,
        esportes: Boolean,
        artes: Boolean,
        outros: { type: Map, of: Boolean },
      },
      profilePicture: String,
      currentJob: {
        empresa: String,
        setor: String,
        cargo: String,
        descricao: String,
        dataInicio: Date,
        dataFim: Date,
      },
      jobs: [
        {
          empresa: String,
          setor: String,
          cargo: String,
          descricao: String,
          dataInicio: Date,
          dataFim: Date,
        },
      ],
      formacao: [
        {
          tipo: String,
          instituicao: String,
          curso: String,
          descricao: String,
          dataInicio: Date,
          dataFim: Date,
        },
      ],
      genero: String,
      idiomas: {
        ingles: String,
        portugues: String,
        espanhol: String,
        alemao: String,
        frances: String,
        outros: { type: Map, of: String },
      },
      idealLocations: { maiorInteresse: String, interesse: [String] },
      funcionarioRh: Boolean,
    },
  ],
  imagensAnexadas: String,
  evento: String,
  postRh: Boolean,
});
